export const USER_FETCH_PRODUCT_TYPE = 'USER_FETCH_PRODUCT_TYPE';
export const USER_FETCH_A_PRODUCT_TYPE = 'USER_FETCH_A_PRODUCT_TYPE';
export const USER_SAVE_PRODUCT_TYPE = 'USER_SAVE_PRODUCT_TYPE';
export const USER_UPDATE_PRODUCT_TYPE = 'USER_UPDATE_PRODUCT_TYPE';
export const USER_DELETE_PRODUCT_TYPE = 'USER_DELETE_PRODUCT_TYPE';
export const SAVE_PRODUCT_TYPE_SUCCESS = 'SAVE_PRODUCT_TYPE_SUCCESS';
export const UPDATE_PRODUCT_TYPE_SUCCESS = 'UPDATE_PRODUCT_TYPE_SUCCESS';
export const FETCH_PRODUCT_TYPE_SUCCESS = 'FETCH_PRODUCT_TYPE_SUCCESS';
export const FETCH_A_PRODUCT_TYPE_SUCCESS = 'FETCH_A_PRODUCT_TYPE_SUCCESS';
export const DELETE_PRODUCT_TYPE_SUCCESS = 'DELETE_PRODUCT_TYPE_SUCCESS';
export const PRODUCT_TYPE_ERROR = 'PRODUCT_TYPE_ERROR';


export const USER_FETCH_PRODUCT = 'USER_FETCH_PRODUCT';
export const USER_FETCH_A_PRODUCT = 'USER_FETCH_A_PRODUCT';
export const USER_SAVE_PRODUCT = 'USER_SAVE_PRODUCT';
export const USER_UPDATE_PRODUCT = 'USER_UPDATE_PRODUCT';
export const USER_DELETE_PRODUCT = 'USER_DELETE_PRODUCT';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_A_PRODUCT_SUCCESS = 'FETCH_A_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';


export const FETCH_BIN_DATA_BY_PRODUCT_SUCCESS = 'FETCH_BIN_DATA_BY_PRODUCT_SUCCESS';
export const USER_FETCH_BIN_DATA_BY_PRODUCT = 'USER_FETCH_BIN_DATA_BY_PRODUCT';